@startuml
left to right direction

package "Hotel Booking" {

    class "<<Application>>\nHotel Booker" as HotelBooker {}

    class "<<Resource>>\nAuth" as ResourceAuth {
        <<POST>> +register(): User
        <<POST>> +login(): Token
        <<GET>> +getMe(): User
    }

    class "<<Representation>>\nUser" as RepresentationUser {
        -name : String
        -tel : String
        -email : String
        -role : String
        -password : String
        -resetPasswordToken : String
        -resetPasswordExpire : Date
        -createdAt : Date
        -isban : Boolean
    }

}

HotelBooker ..> ResourceAuth : "/auth\n<<Path>>"
ResourceAuth ..> RepresentationUser : "<<use>>"

@enduml