@startuml Update Hotel (PUT)

header Hotel Booking Sequence Diagram
footer Page 4 of 13
title "Update Hotel (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<middleware>>\n:protect + authorize" as middlewareAuth
participant "<<controllers>>\n:hotels" as controllersHotels
participant "<<model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelsDatabase

client -> server ++ : req.put('/api/v1/hotels/:id')
server -> routerHotels ++
routerHotels -> middlewareAuth ++ : protect(), authorize('admin')
middlewareAuth -> controllersHotels ++ : updateHotel()

controllersHotels -> modelHotel ++ : findByIdAndUpdate(req.params.id, req.body, {new:true})
modelHotel -> HotelsDatabase ++ : Update document
HotelsDatabase --> modelHotel -- : updated hotel
modelHotel --> controllersHotels -- : updated hotel

controllersHotels -> client -- : response: JSON {success, data: updated hotel}

@enduml