@startuml Delete Hotel (DELETE)

header Hotel Booking Sequence Diagram
footer Page 5 of 13
title "Delete Hotel (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<middleware>>\n:protect" as middlewareAuth
participant "<<controllers>>\n:hotels" as controllersHotels
participant "<<model>>\n:Hotel" as modelHotel
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:hotels" as HotelsDatabase
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client -> server ++ : req.delete('/api/v1/hotels/:id')
server -> routerHotels ++
routerHotels -> middlewareAuth ++ : protect()
middlewareAuth -> controllersHotels ++ : deleteHotel()

controllersHotels -> modelHotel ++ : findById(req.params.id)
modelHotel -> HotelsDatabase ++ : Query document
HotelsDatabase --> modelHotel -- : hotel
modelHotel --> controllersHotels -- : hotel

controllersHotels -> modelBooking ++ : deleteMany({hotel:req.params.id})
modelBooking -> BookingsDatabase ++ : Delete related documents
BookingsDatabase --> modelBooking -- : result
modelBooking --> controllersHotels --

controllersHotels -> modelHotel ++ : deleteOne({_id:req.params.id})
modelHotel -> HotelsDatabase ++ : Delete document
HotelsDatabase --> modelHotel -- : result
modelHotel --> controllersHotels --

controllersHotels -> client -- : response: JSON {success:true, data:{}}

@enduml